# Generated by Django 5.0.4 on 2024-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_review_user_review_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='history_of_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'История компании',
            },
        ),
    ]
