# Generated by Django 5.0.4 on 2024-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_history_of_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='partners/partner.jpg', upload_to='partners')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Компания-партнер',
                'verbose_name_plural': 'Компании-партнеры',
            },
        ),
    ]
