# Generated by Django 5.0.4 on 2024-09-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_cart_client'),
        ('movies_tickets', '0007_remove_cartitem_cart_cartitem_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
