# Generated by Django 5.0.4 on 2024-09-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
